#!/bin/zsh
# custom commands for zsh shell
# quotes aren't necessary to specify strings
# they are provided here for clarity and readability
function affirm() {
	number=$RANDOM
	RANGE=9
	let "number %= $RANGE"
	if [ $number -eq 0 ]
	then
		echo "You are a hard working, strong and diligent person. You are a child of God and He loves you dearly."
	elif [ $number -eq 1 ]
	then
		echo "You can do this. You never give up."
	elif [ $number -eq 2 ]
	then
		echo "You are an excellent programmer. Keep going. You got this."
	elif [ $number -eq 3 ]
	then
		echo "You are bound for success. You are talented and your hard work pays off."
	
	elif [ $number -eq 4 ]
	then 
		echo "Make it happen. You are in control."
	elif [ $number -eq 5 ]
	then 
		echo "\"Success usually comes to those who are too busy to be looking for it.\"
		-- Henry David Thoreau"
	elif [ $number -eq 6 ]
	then 
		echo "\"If you are not willing to risk the usual, you will have to settle for the ordinary.\"
		-- Jim Rohn"
	elif [ $number -eq 7 ]
	then 
		echo "Not far away, there is someone who believes in you. Do it for them."
	elif [ $number -eq 8 ]
	then 
		echo "You can do it!"
	fi
}

function thanks() {
	number=$RANDOM
	RANGE=18
	let "number %= $RANGE"
	if [ $number -eq 0 ]
	then
		echo "But of course."
	elif [ $number -eq 1 ]
	then
		echo "My pleasure."
	elif [ $number -eq 2 ]
	then
		echo "It is I who should be thanking you."
	elif [ $number -eq 3 ]
	then
		echo "You're very welcome, highness.".
	elif [ $number -eq 4 ]
	then
		echo "My greatest pleasure is to serve you."
	elif [ $number -eq 5 ]
	then
		echo "But my sincerest compliments to you."
	elif [ $number -eq 6 ]
	then
		echo "Please, thank you."
	elif [ $number -eq 7 ]
	then
		echo "Your gratitude is heart-warming."
	elif [ $number -eq 8 ]
	then
		echo "May you prosper all your days."
	elif [ $number -eq 9 ]
	then
		echo "Nothing gives me greater joy than to be your computer."
	elif [ $number -eq 10 ]
	then
		echo "You may as well call me Alfred. Or Jarvis."
	elif [ $number -eq 11 ]
	then
		echo "You can always count on me."
	elif [ $number -eq 12 ]
	then
		echo "I am always happy to help."
	elif [ $number -eq 13 ]
	then
		echo "Oh, me? Nah, it was nothing."
	elif [ $number -eq 14 ]
	then
		echo "It is my duty, after all."
	elif [ $number -eq 15 ]
	then
		echo "You would have done the same for me."
	elif [ $number -eq 16 ]
	then
		echo "It was the least I could do."
	elif [ $number -eq 17 ]
	then
		echo "ʕ•ᴥ•ʔ < - - - -  Grateful bear is grateful to be in your computing presence"
	fi
}

# shortcut to run dunnet, the text-based adventure game in emacs
function dunnet() {
	emacs -batch -l dunnet
}

# launch mysql client
function mysql() {
	/usr/local/mysql/bin/mysql -u root -p
}
